spring.application.name=backend-preschool

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/preschool_admin_db_v2?useSSL=false&serverTimezone=Europe/Stockholm&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=BrandelisPreschool_Auth_JWT_SECRET_2026_SuperSecureKey_9xL4pQ8mZ2rT7
app.jwt.expiration-ms=86400000